obj-$(CONFIG_VIDEO_ROCKCHIP_ISP1) += 	video_rkisp1.o
video_rkisp1-objs 	   += 	rkisp1.o \
				dev.o \
				regs.o \
				isp_stats.o \
				isp_params.o \
				capture.o

obj-$(CONFIG_VIDEO_ROCKCHIP_ISP1) += 	video_mipi_dphy_sy.o
video_mipi_dphy_sy-objs 	   += 	mipi_dphy_sy.o
